rating={1: 'Aweful! I am never ever getting this again', 2: 'yeah..meh!', 3: 'kinda ok', 4: 'liked it!', 5:'OMG! felt like i died and went to coffee heaven'}
blends={1:'Italian Roast Blend', 2:'Jamaican Roast', 3:'New Orleans style Chicory Blend', 4:'Dark Roast Columbia', 5:'Indian Coffee House Blend', 6:'American Classic', 7:'Italian Roast', 8:'French Roast', 9:'Classic American', 10:'Decaf'}
types={1:'Mocha', 2:'Latte', 3:'Expresso', 4:'Double expresso', 5:'Capuccino', 6:'Frappuccino'}
sweetness={1:'no sugar', 2:'some sugar', 3:'medium sugar', '4':'high sugar'}
cream={1:'no Cream', 2:'cream'}
milk={1:'no Milk', 2:'Almond milk', 3:'regular milk'}
chocolate={1:'no Chocolate', 2:'white Chocolate', 3:'milk Chocolate', 4:'dark chocolate'}
topping={1:'no toppings', 2:'Whipped cream topping', 3:'chocolate sauce topping', 4:'roasted coffee beans topping'}
personality={1:'Laid-back',2:'Adventurous',3:'Old school'}
accompaniment={1:'A group of friends', 2:'A quiet time alone', 3:'work! work! work!'}
flavors={1:'Roasted nuts', 2:'Cocoa', 3:'Chicory'}